### PR TITLE
SVA 201 Add STA Contact Details

### PR DESCRIPTION
**Pull request by g-dunlop**
- [Description](#description)
  - [Type of change](#type-of-change)
- [Checklist](#checklist)

# Description

Added links to STA privacy policy and terms & conditions at bottom of user account screen (ExampleContainer).  These links open in external browser on the user's device when clicked.

Fixes # (issue number)
SVA-201

## Type of change

Please delete options that are not relevant

- [] New Feature (non-breaking change which adds functionality)

# Checklist

- [] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by joefhall — APPROVED** [review]
Nice one @g-dunlop 🙌  Tested and working on Android

**Comment by joefhall** [comment]
P.S.  If you want to invite some other folks on the team to review (can be quite useful to do, as well as posting on Slack), these are the GitHub usernames of active devs (you can request them by going to Reviewers on the right above and clicking the cog icon):

DougieWougie 
rc-1988 
PammyLo 
CatMac228 
jppferguson 
M4RC1N76

**Review by DougieWougie — CHANGES_REQUESTED** [review]
Looks good @g-dunlop except the new controls aren't visible at all resolutions on Android. EventContainer and HomeContainer both scroll but ExampleContainer doesn't.

Screenshot_1660750037
.

**Comment by g-dunlop** [comment]
Thanks for having a look guys.  @DougieWougie I've commented out what looked to be a redundant 'flex:1' set on the contents of the ScrollView and that seems to enable scrolling without breaking anything on my emulator.  If you get a chance to have another look, please let me know if that's made a difference.  Cheers

**Review by DougieWougie — APPROVED** [review]
Thanks @g-dunlop - that's got it!

**Pull request merged**
