### PR TITLE
SVA-83 | Add event to calendar

### PR DESCRIPTION
**Pull request by joefhall**
- [Description](#description)
  - [Type of change](#type-of-change)
- [Checklist](#checklist)

Screenshot 2022-11-15 15 58 00

Screenshot 2022-11-16 18 11 35

Screenshot 2022-11-16 18 12 11

# Description

- Allow the user to add an upcoming event to their device calendar
- (Assume that once we've added event registration functionality later, this option will only be shown to users who've registered -- you probably wouldn't want to put an event in your calendar that you're not attending)
- Fixed bugs with Redux store that ran into along the way
- Made button and icon components more flexible

Fixes # SVA-83

## Testing
- Have tested on two real Android devices (Samsung Galaxy S10 and Google Pixel 5) and appears to be working as expected
- I'm not sure if/how it'll always work on local test environments (will it find a device calendar on your machine?)
- Would be good to get at least one review from someone using a Mac and iOS simulator as I haven't been able to test on iOS
- To test, make sure to run `npm install` inside the `app` directory first.  Mac users: you'll also need to run `pod install`

## Type of change

Please delete options that are not relevant
- [x] New Feature (non-breaking change which adds functionality)

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by PammyLo — COMMENTED** [review]
Great work Joe. Unfortunately on my mac using the iOS simulator it can't find a calendar. A warning pops up stating "Sorry we ran into a problem accessing your calendar." 
I'll investigate how to test this on iOS.
 
image

**Comment by joefhall** [comment]
Thanks @PammyLo!  Yeah I wonder if it's because there's not a calendar on your laptop in the same way there would be on a real iPhone.   Would you be able to DM me on Slack a .ipa file generated on your Mac?  I have a subscription to an online testing service where I can test on real iOS and Android devices (this is how I did Android testing in the screenshots above).

There are a couple of suggestions here of how to generate a .ipa file:
https://stackoverflow.com/a/63913467/15422951
https://stackoverflow.com/a/43663092/15422951

**Comment by joefhall** [comment]
@PammyLo FYI I've added an extra setting recommended in [the calendar package docs for iOS](https://github.com/wmcmahan/react-native-calendar-events#ios-specific-instructions).  That may not solve your challenges testing locally (not sure - might be for the App Store?), but we could also try my other suggestion mentioned in comment above.

**Comment by PammyLo** [comment]
Hurray :)

Screenshot 2022-11-20 at 22 05 42
image
Screenshot 2022-11-20 at 22 06 10

**Review by PammyLo — APPROVED** [review]
Works as expected on iOS. Great work, thanks @joefhall!

**Comment by joefhall** [comment]
Nice one, thanks @PammyLo ! 😄

**Review by CatMac228 — APPROVED** [review]
Successfully tested on IOS

**Pull request merged**
