### PR TITLE
Remove the network security config for debug builds

### PR DESCRIPTION
**Pull request by rc-1988**
- [Description](#description)
  - [Type of change](#type-of-change)
- [Checklist](#checklist)

# Description

- I'm getting the following error when trying to run the app in the Android emulator:
err3
- Metro is running but the app can't connect to it because the config in `app/android/app/src/main/res/xml/network_security_config.xml` doesn't permit the connection
- For debug builds only, this change removes the android:networkSecurityConfig attribute; we need to keep it in for builds that are released to the Play Store.

## Type of change

Please delete options that are not relevant
- [x] Bug fix (non-breaking change which fixes an issue)
- [] New Feature (non-breaking change which adds functionality)
- [] Breaking change(fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by joefhall** [comment]
Thanks @rc-1988 good catch on this (I haven't had the same problem on my local machine, but maybe different because I'm on Linux).  

The only way I can see to test it on the Google Play Store is to deploy a new release there -- would you be able to follow the steps [in the README](https://github.com/Scottish-Tech-Army/Volunteer-app#app-deployment) on version numbers etc and include that in this PR -- then I can deploy if you want or you can [get set up yourself](https://github.com/Scottish-Tech-Army/Volunteer-app#setup-to-deploy-the-app) and do that.  (If you're doing the deployment, I've just spotted a typo I've made in the setup instructions, will create a separate PR for that now!)

**Comment by rc-1988** [comment]
Added a version bump, which has successfully deployed to the Play Store this evening (thanks @joefhall for your help with that).

You can also confirm that the release build still gets the networkSecurityConfig by doing the following:

1. Open the app/android directory in Android Studio
2. Change to the release build (Build->Select Build Variant and change it from 'debug' to 'release')
3. [View the merged manifest](https://developer.android.com/studio/build/manage-manifests#inspect_the_merged_manifest_and_find_conflicts) to confirm that it's got the android:networkSecurityConfig="@xml/network_security_config" attribute, whereas the merged manifest for the debug build does not

**Review by DougieWougie — APPROVED** [review]
Great work @rc-1988!

**Review by joefhall — APPROVED** [review]
Nice work @rc-1988! 👍

**Review by jppferguson — APPROVED** [review]
Awesome – nice work @rc-1988!

**Pull request merged**
