### PR TITLE
SVA-74 | Events free text search and quick search buttons

### PR DESCRIPTION
**Pull request by joefhall**
- [Description](#description)
  - [Type of change](#type-of-change)
- [Checklist](#checklist)

events-search

# Description

- Enabled events free text search
- Enabled events quick search buttons, updated to use dynamic values
- Refactored some of the events/projects search code and related components to make code reusable / avoid duplication where possible
- Added `related_initiative` field to events (this field is used for one of the quick search buttons). NB although we display this to the user as 'Project Related' events, have suggested naming this in the code as `related_initiative` rather than `related_project` to avoid terminology confusion with projects (everywhere else in the app/API we use `project` as a shorthand to mean a project role e.g. 'Web Developer for ABC Charity Website Redesign', whereas here we're talking about a whole initiative/project e.g. 'ABC Charity Website Redesign').  Obviously please feel free to disagree in the code review if you think we should do it differently / could make it clearer 🙂 

Fixes [SVA-74](https://sta2020.atlassian.net/jira/software/projects/SVA/boards/145?selectedIssue=SVA-74)

## Type of change

- [x] New Feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by DougieWougie — APPROVED** [review]
Been busy @joefhall !

**Review by M4RC1N76 — APPROVED** [review]
I have familiarised myself with the changes in the app components and containers area. I have run the continuous integration test and run the Volunteer App in the emulator. I have also performed a couple of different types of search (using calendar, text search and quick search button). The searches in the App work great!! Excellent work Joe!!

**Comment by M4RC1N76** [comment]
Just a quick question who does the merge of the PR?

**Comment by DougieWougie** [comment]
> Just a quick question who does the merge of the PR?

I always leave it for the originator.

**Comment by M4RC1N76** [comment]
Thanks Dougie👍

Sent from Yahoo Mail on Android 
 
  On Mon, 3 Oct 2022 at 12:21, Dougie ***@***.***> wrote:   



Just a quick question who does the merge of the PR?


I always leave it for the originator.

**Comment by joefhall** [comment]
Thanks both!

@M4RC1N76 if you like, depending on timings I could hold off merging this in for now and do it after you get your PR finished and merged in.  That would save you having to deal with any conflicts with my changes (as there's some overlap between our two PRs).

**Comment by M4RC1N76** [comment]
That is a great idea! I will do my best to change and tidy up the code within next few hours (ideally) or by the end of the day. If you could hold on please, it would be great! Thanks.
    On Tuesday, 4 October 2022 at 10:26:49 BST, Joe Derry Hall ***@***.***> wrote:  
 
 


Thanks both!

@M4RC1N76 if you like, depending on timings I could hold off merging this in for now and do it after you get your PR finished and merged in. That would save you having to deal with any conflicts with my changes (as there's some overlap between our two PRs).

**Pull request merged**
