### PR TITLE
SVA-238 | Fix for React Native Android build failure

### PR DESCRIPTION
**Pull request by joefhall**
- [Description](#description)
  - [Type of change](#type-of-change)
- [Checklist](#checklist)

# Description

- There is a new known [issue](https://stackoverflow.com/questions/74325532/react-native-app-not-running-without-doing-anything-in-the-previous-working-code) that can cause the React Native Android build process to fail
- Implemented [the recommended fix](https://github.com/facebook/react-native/issues/35210)

Fixes SVA-238

## Type of change

Please delete options that are not relevant
- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by DougieWougie — COMMENTED** [review]
Great spot @joefhall - build on Android under Windows and Ubuntu 20.04. 

Some might also see "_> java.lang.OutOfMemoryError (no error message)_" on Android but closing any running apps on the emulator fixed that.

**Review by DougieWougie — APPROVED** [review]
Meant to choose Approve. D'oh.

**Review by annabergin94 — APPROVED** [review]
This works for me locally and fixes issues I've been having building the app

**Comment by joefhall** [comment]
Thanks @DougieWougie and @annabergin94!

**Review by sugaith — COMMENTED** [review]
Tested here for RN 0.66.0

**Pull request merged**
