### PR TITLE
SVA-82 | See event detail

### PR DESCRIPTION
**Pull request by joefhall**
- [Description](#description)
  - [Type of change](#type-of-change)
- [Checklist](#checklist)

Screenshot 2022-08-26 11 43 51

Screenshot 2022-08-26 11 44 42

Screenshot 2022-08-26 11 43 15

# Description

- Add event details screen
- Get event video files and thumbnails from Vimeo
- Show event video/image(s) on details screen
- Improve how events appear in events list
- Made as many components as reusable as possible
- Renamed `/api/cache` to `/api/cron-jobs` so it's more accurate

Solves tickets SVA-82 and SVA-109 (which are basically the same)

# Testing notes

Make sure to run `npm install` in your `/app` directory.

As we don't have scheduled cron jobs up and running yet, to get event videos to work you'll need to go to `/api` and run the command `node cron-jobs/run-events.js` when you want to test (this pulls in video URLs from Vimeo that expire after an hour).  Only one test event in upcoming events has a video.

Microsoft power bi event shows the image swiper working (for when an event has multiple images).

Microsoft power bi and Data Collective events show markdown formatting working (link and bolding in this case).

## Type of change

Please delete options that are not relevant
- [x] New Feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by DougieWougie — COMMENTED** [review]
Great stuff @joefhall - minor observations:

1. At lower resolutions, some data overlaps.
2. Should I see a thumbnail on the events page (like yours)?

**Review by g-dunlop — COMMENTED** [review]
This looks great!  Everything's working well for me.  I'm getting overlap on the pagination item too at higher resolution but the thumbnail is showing.

**Comment by joefhall** [comment]
Thanks for reviewing @DougieWougie and @g-dunlop -- will take a look at the pagination overlap, that doesn't happen for me.

@DougieWougie are you still getting that thumbnail image not showing on 'Test event showing video'?  It should be there, just wondered if maybe it didn't load for you before as a one-off (e.g. internet connection problem).

**Comment by DougieWougie** [comment]
> Thanks for reviewing @DougieWougie and @g-dunlop -- will take a look at the pagination overlap, that doesn't happen for me.
> 
> @DougieWougie are you still getting that thumbnail image not showing on 'Test event showing video'? It should be there, just wondered if maybe it didn't load for you before as a one-off (e.g. internet connection problem).

Hi @joefhall, pulled and ran the cron job - still getting the same missing thumbnail. I might try a different resolution on an emulator and see what happens.

**Review by DougieWougie — APPROVED** [review]
That's got it @joefhall - great stuff!

**Comment by joefhall** [comment]
Hi @DougieWougie @g-dunlop I've pushed a couple of changes which I'm hoping might fix the issues you spotted before.

@DougieWougie the one I'm least certain about is where you found in the list of events the image wasn't displaying on 'Test event showing video'.  I did notice that the URL for the image filename didn't include an extension (.jpg) so I wondered if that's what was causing a problem -- I've added a fix for this now to force there to be one, be great if you could see if it rectifies it.  (If that doesn't solve it, I wonder if it's maybe instead because the image is in a different JPEG format that for some reason isn't being displayed -- can investigate more if it's still not showing up.)

Thanks!

**Comment by joefhall** [comment]
Ah amazing, thanks @DougieWougie -- that's great it's working!

@g-dunlop if you're ok to re-review too when you have a moment, that would be grand, thanks

**Comment by DougieWougie** [comment]
Thumbnail is there, I managed a pull just after the last commit!

**Comment by joefhall** [comment]
Brilliant thanks, yep our PR comments just overlapped!

**Review by g-dunlop — APPROVED** [review]
@joefhall That's fixed the pagination overlap I was seeing before.  Nice one!

**Review by M4RC1N76 — APPROVED** [review]
I have went through all of the files which were changed, partially removed or whole new files added. It is a huge work you have done on the server and frontend side.I am now aware that the JIRA API are too slow, hence the use of AirTables. After the recent git pull and update of my branch I was able to observe the changes of images and videos. Great work Joe. Frontend work look impressive too.

**Comment by joefhall** [comment]
Thanks @M4RC1N76!  And great to hear you've been able to get things working on your local machine, I'm sure that's a relief.

**Pull request merged**
