### PR TITLE
Fix README typo in Google Play Store setup instructions

### PR DESCRIPTION
**Pull request by joefhall**
- [Description](#description)
  - [Type of change](#type-of-change)
- [Checklist](#checklist)

# Description

- Fix typo in name of key file in Google Play Store setup instructions (so it matches [the filename Fastlane looks for](https://github.com/Scottish-Tech-Army/Volunteer-app/blob/main/app/android/fastlane/Fastfile#L28) when deploying)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by DougieWougie — APPROVED** [review]
Pesky typos!

**Comment by rc-1988** [comment]
Nice one @joefhall! That is indeed an important one :)

**Review by rc-1988 — APPROVED** [review]
All good!

**Comment by joefhall** [comment]
Cheers @DougieWougie and @rc-1988! 🙌

**Pull request merged**
