### PR TITLE
SVA-170 | Stop API returning dummy projects data if it hits an error, remove unused files

### PR DESCRIPTION
**Pull request by joefhall**
- [Description](#description)
  - [Type of change](#type-of-change)
- [Checklist](#checklist)

# Description

- We had previously set up the projects API route to return dummy data if it ran into an error (this was because the error was usually that a new developer on the team didn't have the right .env details, this was a quick fix so that team members could get up and running quickly)
- But we don't want the API to be able to return dummy data when it's starting to be used with real app users, and we can help new team members get set up properly in other ways so they shouldn't need this
- Have tweaked error messages that the API returns to make sure these are helpful
- Have also taken the opportunity to remove a few API files that are no longer in use (some related to sample data)

Fixes [SVA-170](https://sta2020.atlassian.net/jira/software/projects/SVA/boards/145?selectedIssue=SVA-170)

## Type of change

Please delete options that are not relevant
- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by DougieWougie — COMMENTED** [review]
No issues!

**Comment by joefhall** [comment]
Thanks @DougieWougie! 👍

**Review by PammyLo — APPROVED** [review]
Excellent @joefhall, thanks for the thorough tidy up!

**Comment by joefhall** [comment]
Gracias @PammyLo!

**Pull request merged**
