### PR TITLE
Feature/sva 81 get events from airtable

### PR DESCRIPTION
**Pull request by stevenjburrows**
- [Description](#description)
  - [Type of change](#type-of-change)
- [Checklist](#checklist)

# Description

added the ability to call the Airtable API and return events.  I made the code so that should the need arise we can add other calls to different tables very easily

## Type of change

Please delete options that are not relevant
- [] Bug fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [] Breaking change(fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, pariculary in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by CatMac228 — APPROVED** [review]

**Comment by keithdhd** [comment]
@stevenjburrows we got this error trying to start the server.js. Maybe we need to configure something first?

`> volunteer-app-api@1.0.0 start
> nodemon server.js

[nodemon] 2.0.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
file:///Users/keithdouglas/Documents/sta/Volunteer-app/api/server.js:1
const app = require("./app");
            ^

ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/Users/keithdouglas/Documents/sta/Volunteer-app/api/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///Users/keithdouglas/Documents/sta/Volunteer-app/api/server.js:1:13
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
[nodemon] app crashed - waiting for file changes before starting...`

**Comment by stevenjburrows** [comment]
> @stevenjburrows we got this error trying to start the server.js. In package.json type: "module" means we use import rather than require I think?
> 
> Using node v17.0.1
> 
> `> volunteer-app-api@1.0.0 start
> 
> > nodemon server.js
> 
> [nodemon] 2.0.12 [nodemon] to restart at any time, enter `rs` [nodemon] watching path(s): _._ [nodemon] watching extensions: js,mjs,json [nodemon] starting `node server.js` file:///Users/keithdouglas/Documents/sta/Volunteer-app/api/server.js:1 const app = require("./app"); ^
> 
> ReferenceError: require is not defined in ES module scope, you can use import instead This file is being treated as an ES module because it has a '.js' file extension and '/Users/keithdouglas/Documents/sta/Volunteer-app/api/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension. at file:///Users/keithdouglas/Documents/sta/Volunteer-app/api/server.js:1:13 at ModuleJob.run (node:internal/modules/esm/module_job:185:25) at async Promise.all (index 0) at async ESMLoader.import (node:internal/modules/esm/loader:281:24) at async loadESM (node:internal/process/esm_loader:88:5) at async handleMainPromise (node:internal/modules/run_main:65:12) [nodemon] app crashed - waiting for file changes before starting...`

@keithdhd You are right, I forgot I had added it when I was trying to get the tests to work.  I have removed it and it is working now.  Can you take another look

**Comment by keithdhd** [comment]
Thanks @stevenjburrows. 

All the tests run but I don't have the AIRTABLE_API_KEY and AIRTABLE_ID so I can't test the route. Are these available somewhere so I can plug them in or is it ok to approve the PR without them?

**Comment by stevenjburrows** [comment]
@keithdhd i created my own api key using my account.  The id is in a document in slack

**Review by keithdhd — APPROVED** [review]

**Pull request merged**
