### PR TITLE
SVA 310

### PR DESCRIPTION
**Pull request by vglampard**
- [Description](#description)
  - [Type of change](#type-of-change)
- [Testing locally](#testing-locally)
- [Checklist](#checklist)

# Description

Just switched my old friend the welcome screen text back from lorem ipsum to the real phrases. 

Fixes #SVA-310

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Testing locally

I ran the emulator, but the welcome screens aren't visible (presumably because of the feature that hides them when the user has already visited the app).

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have removed any unnecessary comments or console logging
- [x] I have made corresponding changes to the documentation (if required)
- [x] I have addressed accessibility, if needed
- [x] I have followed best practices, e.g. NativeBase approaches and theming
- [x] I have checked the app in dark mode, if making front-end design changes
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by kelsiesmurphy** [comment]
Before I add a review, I also couldn't view the welcome screens. @DougieWougie or @joefhall is there something we're missing to verify these changes in-app?

**Review by kelsiesmurphy — CHANGES_REQUESTED** [review]
I notice the quotation marks have changed from single quotes to double quotes, I believe it should still be single, right? I know I've done this a few times, so wanted to check.

**Comment by joefhall** [comment]
> Before I add a review, I also couldn't view the welcome screens. @DougieWougie or @joefhall is there something we're missing to verify these changes in-app?

Yep @kelsiesmurphy @vglampard to see the welcome screens you can do it by temporarily uncommenting the 'Show welcome screen on startup' setting in ProfileContainer (and related lines of code further up that file that it relies on), then tick that box on the settings screen, then close the app and restart it.

**Comment by joefhall** [comment]
> I notice the quotation marks have changed from single quotes to double quotes, I believe it should still be single, right? I know I've done this a few times, so wanted to check.

Yes exactly right -- these should be single quotes.  

(@vglampard if you're using VS Code, do you have the ES Lint extension and the [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) extension with the format on save setting enabled?  It should normally auto-correct common things like this so you don't have to worry about it.)

**Comment by joefhall** [comment]
> > I notice the quotation marks have changed from single quotes to double quotes, I believe it should still be single, right? I know I've done this a few times, so wanted to check.
> 
> Yes exactly right -- these should be single quotes.
> 
> (@vglampard if you're using VS Code, do you have the ES Lint extension and the [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) extension with the format on save setting enabled? It should normally auto-correct common things like this so you don't have to worry about it.)

No, actually, I'm talking rubbish! 😄   Sorry @vglampard @kelsiesmurphy  Because these two bits of text have apostrophes (aka single quotes) in the text, it's right to use double quotes here.

**Review by joefhall — APPROVED** [review]
Looks good -- thanks for (re)doing that @vglampard!

**Review by kelsiesmurphy — APPROVED** [review]
Checked it out in the emulator, and it works! And thanks @joefhall for the response re: single vs double quotes

**Comment by joefhall** [comment]
> Checked it out in the emulator, and it works! And thanks @joefhall for the response re: single vs double quotes

All good, thanks for the eagle-eyed checking @kelsiesmurphy (and thanks @vglampard for picking up this ticket)

**Comment by vglampard** [comment]
Very nice, thank you both! 💪💪💪

**Pull request merged**
