### PR TITLE
SVA-40 | Enable search by project role

### PR DESCRIPTION
**Pull request by joefhall**
- [Description](#description)
  - [Type of change](#type-of-change)
- [Checklist](#checklist)

Search by role - results found
Search by role - none found

# Description

- When searching for a project, allows you to tap on one of the buttons for common role searches (e.g. "Web Developer") and display search results
- Match related role names to improve search results
- Add fuzzy text searching to improve search results
- Improve project search results page to show a message when no results are found
- (Also tidied up spelling typos in the pull request template, as I realised I end up correcting these manually each time! 🙂)

Ticket: [SVA-40](https://sta2020.atlassian.net/jira/software/projects/SVA/boards/145?selectedIssue=SVA-40)

## Type of change

- [x] New Feature (non-breaking change which adds functionality)

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by DougieWougie — APPROVED** [review]
Splendid work Joe! No issues on Android, works great.

**Review by CatMac228 — APPROVED** [review]
Works on IOS :)

**Comment by joefhall** [comment]
Hi @DougieWougie @CatMac228 thanks for reviewing!  

Joanna has given me some new info about how different role names are used, so I've updated the code to enable matching similar but differently named roles, and have added fuzzy text search so the search is better able to match e.g. different spellings / non-exact matches.

Technically GitHub will let me merge this in without another review, but I think it's good practice - could you take another look to check you're happy?  Many thanks

**Comment by hqureshi88** [comment]
Tried testing it on my machine using ios, but keeps showing loading.... It might be how i set up but will wait for others.

**Comment by joefhall** [comment]
Hi @hqureshi88 that sounds like an issue with the app connecting to the API.  Do you have the API running?  Do you have a `app/src/Config/index.ts` file?  If yes to both of those, see also step 10 in the README under 'Set up and first run', there are one or two tips there.  Fingers crossed that'll work for you!

**Comment by hqureshi88** [comment]
Ah! its because i forgot to change the localhost! It works now with IOS. I tested the search as well and looks good! 👍

**Comment by joefhall** [comment]
Ah great!  Lovely, thanks @hqureshi88!

**Comment by DougieWougie** [comment]
> Hi @DougieWougie @CatMac228 thanks for reviewing!
> 
> Joanna has given me some new info about how different role names are used, so I've updated the code to enable matching similar but differently named roles, and have added fuzzy text search so the search is better able to match e.g. different spellings / non-exact matches.
> 
> Technically GitHub will let me merge this in without another review, but I think it's good practice - could you take another look to check you're happy? Many thanks

Pulled, checked and it's all good!

**Comment by joefhall** [comment]
Thanks a lot @DougieWougie @CatMac228 @hqureshi88 -- appreciate that!

**Pull request merged**
