### PR TITLE
Feature/SVA-13 welcome info display welcome page (and SVA-14 & 15)

### PR DESCRIPTION
**Pull request by g-dunlop**
- [Description](#description)
  - [Type of change](#type-of-change)
- [Checklist](#checklist)

# Description

-Have added a welcome slider for 'welcome', 'volunteer', 'make an impact' pages.  User should be able to move between the pages by swiping or clicking the dots.  In future this should only appear if user isn't signed in but for now have set to navigate to slider from StartupContainer and then to HomeContainer when clicking 'get started'.  

No dependencies but have linked some fonts in react-native.config.js.  You may need to run 'npx react-native link' in /app before running it.  I'm not sure if this is something each of us has to do locally if someone could test that.  Also, if there's a more appropriate way to add fonts into the app, let me know!

Fixes # (issue number)
SVA-13, 14, 15

## Type of change

Please delete options that are not relevant

- [x] New Feature (non-breaking change which adds functionality)

# Checklist

- [] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by DougieWougie — CHANGES_REQUESTED** [review]
Hi @g-dunlop - looks like a good start and I really like that you've organised the files in a folder (makes it really clear what those containers do). Some observations:

- The welcome screen is the same in Dark and Light mode.
- Most of the code is self-documenting but just a brief note at the top of each file, how the connect etc would be great.
- Could we add state to StartupContainer.tsx so that the welcome screen isn't shown every time? Maybe each update or only on first run?
- Text is cut off in lower resolutions

**Comment by g-dunlop** [comment]
@DougieWougie Thanks for the review!  I'll add comments at top of component files and will try to make the screen responsive as I guess this one shouldn't be a page that the user scrolls.  Joe's sent me a logo for dark mode so I'll have a crack at that today.

With regards to state, do you have any advice for how to go about it at this stage?  I wasn't sure if that would rely on having auth set up or not.

Thanks!

**Review by M4RC1N76 — APPROVED** [review]
Hi Graeme, I have re-run all tests with a pass. I have also viewed all the entries form your PR list. I admire the way you write the code its clean well structured. I have seen the images, nice work. The only think I couldn't do is run the app, however I have familiarise myself with Dougie's review and have seen a the emulator view of the 'Welcome Page'. Great work.

**Comment by DougieWougie** [comment]
> @DougieWougie Thanks for the review!  I'll add comments at top of component files and will try to make the screen responsive as I guess this one shouldn't be a page that the user scrolls.  Joe's sent me a logo for dark mode so I'll have a crack at that today.
> 
> With regards to state, do you have any advice for how to go about it at this stage?  I wasn't sure if that would rely on having auth set up or not.
> 
> Thanks!

Probably worth a separate ticket, it's a job for AsyncStorage, deprecated from React Native and now community managed.

If I remember, it was also one of the dependencies causing issues.

**Comment by g-dunlop** [comment]
Hi, I have pushed changes based on your suggestions @DougieWougie.   Thanks @M4RC1N76 for the review and feedback!  It's probably good to get two reviews from this point if anyone has time.  

It would be good to confirm if you have to run 'npx react-native link' in the command line (/app folder) or if the app works for you without doing so.  After updating my branch with main I got a 'Failed to Load Script' error in the emulator but running the above command seemed to fix it.

I will make a ticket for creating state to show welcome screen on first run only.  Cheers!

**Comment by M4RC1N76** [comment]
The API starts fine and I can see your updates in the Chrome localhost:3000/projects. These are the warnings and messages I am receiving (when running (npm run android) in the app side. I have done the git pull to be up to date with the main branch. I have tried npx react-native link as suggested with no luck. Any suggestions? Let me know, please?

**Comment by g-dunlop** [comment]
> 

Did you mean to attach the error messages?  I can't see them.  Is the main branch currently working for you?

**Review by DougieWougie — APPROVED** [review]

**Comment by DougieWougie** [comment]
That's awesome @g-dunlop - probably the best looking screen in the app at the moment!

**Comment by M4RC1N76** [comment]
Great work Graeme!! As we discussed the 'Welcome Section' looks great and works perfect. As you said if you thinking of working on the logic to display the 'Welcome Section' just once for a new people interested in the projects go for it.

**Comment by g-dunlop** [comment]
Thanks @M4RC1N76 and @DougieWougie for the reviews!

**Pull request merged**
