### PR TITLE
Sva 301

### PR DESCRIPTION
**Pull request by vglampard**
- [Description](#description)
  - [Type of change](#type-of-change)
- [Testing locally](#testing-locally)
- [Checklist](#checklist)

# Description

Linked up a new webhook so that the API production server is sending messages to the real initial-triage channel on slack, and not initial-triage-test.

This also meant changing the github secret for SLACK_CHANNEL_VOLUNTEER_PROJECT_INTEREST and adding one for SLACK_SECRET_WEBHOOK_INITIAL_TRIAGE. 

Also added a bit in the slack section of the readme so that users know to add a line to the workflows/ci_api.yml file when linking up a new webhook. 

Fixes # SVA-301

## Type of change

Please delete options that are not relevant

- [x] Breaking change(fix or feature that would cause existing functionality to not work as expected)

NB: have messaged all devs to make sure their STA_BASE_URL variable in their index.ts file is pointing towards their local API server instead of the production one. Otherwise this will result in messages being sent to the real initial-triage channel when the app is being tested on the emulator.

# Testing locally

- The API should automatically redeploy when this PR is merged to main, and once it does it can be tested by opening the app, registering interest in a project, and checking that it's coming through to the initial-triage slack channel. So it has not yet been tested, but I can sort this once it's merged and the API redeployed.

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have removed any unnecessary comments or console logging
- [x] I have made corresponding changes to the documentation (if required)
- [x] I have addressed accessibility, if needed
- [x] I have followed best practices, e.g. NativeBase approaches and theming
- [x] I have checked the app in dark mode, if making front-end design changes
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by DougieWougie — APPROVED** [review]
Thanks @vglampard - remember to replace DEPLOY_ENV_FILE with the updated .env contents for the CD to deploy the API correctly!

**Comment by vglampard** [comment]
> Thanks @vglampard - remember to replace DEPLOY_ENV_FILE with the updated .env contents for the CD to deploy the API correctly!

OK, think that's all done!

**Review by M4RC1N76 — APPROVED** [review]
Hi @vglampard  I have familiarised myself with the changes in the .github/worlflows/ci_api.yml and readme file, nice work!!

**Review by joefhall — CHANGES_REQUESTED** [review]
Thanks @vglampard good stuff!

I've just spotted that the new secret `SLACK_SECRET_WEBHOOK_INITIAL_TRIAGE` hasn't been added into our [GitHub actions secrets](https://github.com/Scottish-Tech-Army/Volunteer-app/settings/secrets/actions) (apologies if this wasn't included on the Jira ticket).  Please could you do that and also add that as an extra step in the README instructions.

**Comment by vglampard** [comment]
Oh sorry - you DID put it in the ticket details and I THOUGHT I had done it, but obviously no dice. It should be changed now - and I've added it to the readme

**Comment by joefhall** [comment]
@vglampard nice one, thanks!

NB if you're testing this with Joanna, I think it will only post messages to the actual `initial-triage` channel either
a) before (or after) you've merged the PR, from your emulator running your local API server (assuming you've got the new variable in your `api/.env` file)
or
b) after the PR's been merged which re-deploys  the API server with these changes, from the actual app on Joanna's (or your) phone

b) would be the best actual test, but you could try a) first too if you want just in case there's any other code that needs updating

**Review by joefhall — APPROVED** [review]

**Comment by vglampard** [comment]
Perfect - have merged this, will check with Dougie that it's redeployed, and will get testflight set up (and for efficiency's sake maybe ask joanna to shoot a quick test over with the testflight). Thanks for your help!

**Pull request merged**
