### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jppferguson**
- [Description](#description)
  - [Type of change](#type-of-change)
- [Checklist](#checklist)

# Description

- Please include a summary of the change and which issue is fixed.
- List any dependencies that are required for this change.

Fixes # (issue number)

## Type of change

Please delete options that are not relevant
- [] Bug fix (non-breaking change which fixes an isssue)
- [] New Feature (non-breaking change which adds functionlity)
- [] Breaking change(fix or feature that would cause existing functionlity to not work as expected)
- [] This change requires a documentation update

# Checklist

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, pariculary in hard-to-understand areas
- [] I have made corresponding changes to the documentation (if required)
- [] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by stevenjburrows** [comment]
@jppferguson I have had a look at the readme file and I didn't follow it.  In step 5 it mentions the client folder but there is none within the app folder should it say

> Note: Inside app folder

**Comment by jppferguson** [comment]
> @jppferguson I have had a look at the readme file and I didn't follow it. In step 5 it mentions the client folder but there is none within the app folder should it say
> 
> > Note: Inside app folder

Thanks, yes you're correct – looks like I missed that one!

**Review by stevenjburrows — APPROVED** [review]
Looks good to me

**Comment by GaganSingh5** [comment]
I think we can also add, that we to run the backend stub server in app folder as I was getting network error and nothing was coming on the screen

**Review by GaganSingh5 — COMMENTED** [review]
Looks fine to me

**Review by GaganSingh5 — APPROVED** [review]

**Pull request merged**
