### PR TITLE
Same light and dark splash screen

### PR DESCRIPTION
**Pull request by DougieWougie**
Removed an externally linked image from boilerplate dark theme.

- [Description](#description)
  - [Type of change](#type-of-change)
- [Checklist](#checklist)

# Description

- Splash screen branding is now the same in dark and light themes.

Fixes # (issue number)

## Type of change

Please delete options that are not relevant
- [X] Bug fix (non-breaking change which fixes an issue)
- [] New Feature (non-breaking change which adds functionality)
- [] Breaking change(fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

# Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation (if required)
- [X] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by rc-1988 — CHANGES_REQUESTED** [review]
Thanks @DougieWougie - this removes the octopus tentacle and replaces it with the STA logo, and looks like it does the same in the ExampleContainer too which is great.

The splash screens aren't quite the same though since the welcome text isn't showing in dark mode. I suspect this is because it's text with no colour specified so it defaults to black, on a black background set by the dark theme. In `app/src/Containers/StartupContainer.tsx`, if you replace

`<Text style={Fonts.textCenter}>{t('welcome')}</Text>`

with e.g.

`<Text style={[Fonts.textCenter, Fonts.textSmall]}>{t('welcome')}</Text>`

then that should pull in the textSmall style from the current theme, which includes setting the text colour to whatever is the default for that theme - currently white in dark mode and #212529 (dark grey) in light mode.

**Comment by DougieWougie** [comment]
Rosie's PR #77 changes are needed to run this in the Android Emulator.

**Review by rc-1988 — APPROVED** [review]
Nice one @DougieWougie !

**Comment by joefhall** [comment]
The code looks good, but I can't test this properly on my device (I run it as a real Android app on my Chromebook, and Chromebooks don't have a proper dark mode yet, a bit behind the times! 🤷‍♂️)

**Comment by PammyLo** [comment]
Works on iOS @DougieWougie, great work! Only improvement would be to use a logo that has 'Scottish Tech Army' in white as the standard font is too dark for a dark background.

**Comment by DougieWougie** [comment]
> Works on iOS @DougieWougie, great work! Only improvement would be to use a logo that has 'Scottish Tech Army' in white as the standard logo font is too dark for a dark background.

Fair one - see what I can manage with Paint...

**Comment by joefhall** [comment]
> > Works on iOS @DougieWougie, great work! Only improvement would be to use a logo that has 'Scottish Tech Army' in white as the standard logo font is too dark for a dark background.
> 
> Fair one - see what I can manage with Paint...

@DougieWougie if you need any help, I have a Photoshop equivalent and can have a go

**Comment by DougieWougie** [comment]
> > > Works on iOS @DougieWougie, great work! Only improvement would be to use a logo that has 'Scottish Tech Army' in white as the standard logo font is too dark for a dark background.
> > 
> > 
> > Fair one - see what I can manage with Paint...
> 
> @DougieWougie if you need any help, I have a Photoshop equivalent and can have a go

That'd be great @joefhall - I've all the artistic ability of a cluster of colourblind hedgehogs, in a bag.

**Comment by joefhall** [comment]
> > > > Works on iOS @DougieWougie, great work! Only improvement would be to use a logo that has 'Scottish Tech Army' in white as the standard logo font is too dark for a dark background.
> > > 
> > > 
> > > Fair one - see what I can manage with Paint...
> > 
> > 
> > @DougieWougie if you need any help, I have a Photoshop equivalent and can have a go
> 
> That'd be great @joefhall - I've all the artistic ability of a cluster of colourblind hedgehogs, in a bag.

😂  Is this the one you need or is it something else?

LongLogo-dark

**Comment by DougieWougie** [comment]
Awesome @joefhall thanks!

**Comment by rc-1988** [comment]
> That'd be great @joefhall - I've all the artistic ability of a cluster of colourblind hedgehogs, in a bag.

If true, you more than make up for it in your way with words 😂

**Comment by DougieWougie** [comment]
@joefhall new dark bg logo in there and it shows up on the settings screen too.

**Comment by joefhall** [comment]
> @joefhall new dark bg logo in there and it shows up on the settings screen too.

Nice one!  As before, I can't review this unfortunately because my Chromebook doesn't have a true dark mode setting, but hopefully others can if you need them to.

**Review by jppferguson — APPROVED** [review]
Nice one @DougieWougie , looks all good to me on both iOS and Android on Dark and Light modes:
Simulator Screen Shot - iPhone 13 - 2022-08-01 at 22 54 12
Simulator Screen Shot - iPhone 13 - 2022-08-01 at 22 54 41
Screenshot_1659391426
Screenshot_1659391445

**Pull request merged**
