### PR TITLE
Fixes SVA#291 - Register Interest Button not fixed in position

### PR DESCRIPTION
**Pull request by DougieWougie**
- [Description](#description)
  - [Type of change](#type-of-change)
- [Testing locally](#testing-locally)
- [Checklist](#checklist)

# Description

- Moved the ScrollView from ProjectRegisterInterestContainer to ProjectRegisterInterest because (a) it allows the button to remain in the same postion and (b) if additional components are added to the form, the previous paradigm left the button floating on top of other components.
- Doesn't change any dependencies.

Fixes #SVA-291

## Type of change

Please delete options that are not relevant

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New Feature (non-breaking change which adds functionality)
- [] Breaking change(fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

# Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have removed any unnecessary comments or console logging
- [] I have made corresponding changes to the documentation (if required)
- [] I have addressed accessibility, if needed
- [X] I have followed best practices, e.g. NativeBase approaches and theming
- [X] I have checked the app in dark mode, if making front-end design changes
- [X] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by M4RC1N76** [comment]
***@***.*** I was testing your ticket and by the design everything looks good. There is a little glitch I have noticed when trying to register with two projects. One is The Healthiest Town the second is Alzheimer Scotland. When I press register interest button it kicks me out of the App. I know that your ticket is associated with the design, however could you let me know I you have the same problem, please? It might be a possible spike ticket to fix the function somewhere in the app. 

    On Sunday, 16 April 2023 at 11:23:08 BST, Dougie Richardson ***@***.***> wrote:  
 
 


@DougieWougie requested your review on: #140 Fixes SVA#291 - Register Interest Button not fixed in position.

**Comment by M4RC1N76** [comment]
Hi [@DougieWougie](https://github.com/DougieWougie) I was testing your ticket and by the design everything looks good. There is a little glitch I have noticed when trying to register with two projects. One is The Healthiest Town the second is Alzheimer Scotland. When I press register interest button it kicks me out of the App. I know that your ticket is associated with the design, however could you let me know I you have the same problem, please? It might be a possible spike ticket to fix the function somewhere in the app.

**Comment by DougieWougie** [comment]
Thanks @M4RC1N76.

I noticed crashes with those two projects. That's not caused by this PR (I checked main), it's a separate problem I think related to a change in one of the definitions that hasn't had its associated type updated.

**Review by M4RC1N76 — APPROVED** [review]
Nice one @DougieWougie !!

**Review by joefhall — APPROVED** [review]
Nice one, thanks @DougieWougie -- looks good!

**Pull request merged**
