### PR TITLE
SVA-175 | Added A3 Scope Jira field

### PR DESCRIPTION
**Pull request by CatMac228**
- [Description](#description)
- [Checklist](#checklist)

Fixes # [issue number](https://sta2020.atlassian.net/browse/SVA-175)

## Description
 - Added A3 Scope Doc to the Jira Project Data array

## Type of change

Please delete options that are not relevant
- [] Bug fix (non-breaking change which fixes an isssue)
- [x] New Feature (non-breaking change which adds functionlity)
- [] Breaking change(fix or feature that would cause existing functionlity to not work as expected)
- [] This change requires a documentation update

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [] I have commented my code, pariculary in hard-to-understand areas
- [] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes

Screenshot 2022-03-30 at 15 54 36

### CODE REVIEW

**Comment by joefhall** [comment]
Thanks for this, looks good so far in getting this new data field into the AirTable cache.  I was getting an error when I ran the cache script (`node cache/run-projects.js` from the `api` directory) because the `scope` field wasn't set up in AirTable, but I've added that now in [the AirTable table.](https://airtable.com/appcvHsm6PC8mZth2/tblIWY4PCf6kxn4N4/viwIz02arOMbyXwyw?blocks=hide)

Am I right in thinking this should return a link to a document e.g. a PDF (maybe stored on Google Drive) that an app user could view?  In the data coming through, I can see two projects that have this `scope` URL set, and both seem to point to wiki pages in a restricted area of Jira -- does that look right?
`it_key` IT-340 - `res_id` 15284 - `scope` https://sta2020.atlassian.net/wiki/spaces/SKI
`it_key` IT-471 - `res_id` 14523 - `scope` https://sta2020.atlassian.net/wiki/spaces/ART

Also I think there are a few other places that need updating -- appreciate this may not have been clear with the new way the projects caching is set up:

- [/api/definitions/api_definition.json](https://github.com/Scottish-Tech-Army/Volunteer-app/blob/main/api/definitions/api_definition.json) -- so that the API data definition is up to date, and because the definition file is also used by [/api/helpers/projects.js](https://github.com/Scottish-Tech-Army/Volunteer-app/blob/main/api/helpers/projects.js) to format the data / check which fields should be included
- [/api/sample-data/projects.json](https://github.com/Scottish-Tech-Army/Volunteer-app/blob/main/api/sample-data/projects.json) -- this shows sample projects data
- [/api/__test-data__/projects.js](https://github.com/Scottish-Tech-Army/Volunteer-app/blob/main/api/__test-data__/projects.js) -- this creates dummy data for tests, it needs the `scope` field adding in a few places (probably everywhere there's also the `video` field)
- And once that last one's done, I think at least one of the tests in [/api/__tests__/cache/projects.test.js](https://github.com/Scottish-Tech-Army/Volunteer-app/blob/main/api/__tests__/cache/projects.test.js) will also need updating

**Comment by CatMac228** [comment]
Thanks for checking! Have converted this to a draft for now - got a new laptop and still getting the boilerplate set up so just looked at the reponse back from API, didn't realise other places would need updated - my bad! Hoping to finish the set-up tonight then will make those other changes.

The example ticket I used just had a Google Drive link...possibly other tickets might be using the Jira field for the WIKI pages or they haven't been updated yet...

**Review by joefhall — COMMENTED** [review]
Looks good!  I think there are a few places that still need updating:

- 'getInitialTriageProjectsFromJira calls Jira API' test also needs to check to see if `scope` is included [here](https://github.com/Scottish-Tech-Army/Volunteer-app/blob/main/api/__tests__/cache/projects.test.js#L314)
- There's [a file which creates test data for projects tests to use](https://github.com/Scottish-Tech-Army/Volunteer-app/blob/main/api/__test-data__/projects.js) which needs `scope` adding - [here](https://github.com/Scottish-Tech-Army/Volunteer-app/blob/main/api/__test-data__/projects.js#L28) and [here](https://github.com/Scottish-Tech-Army/Volunteer-app/blob/main/api/__test-data__/projects.js#L85) and [here](https://github.com/Scottish-Tech-Army/Volunteer-app/blob/main/api/__test-data__/projects.js#L166) I think (basically any objects where it's already providing a `video` property I think we need to add `scope` too?)

**Comment by joefhall** [comment]
Give me a shout if any of that's not clear.  Where you see `faker` that's [this library](https://fakerjs.dev/guide/) which is handy for creating dummy data for testing - e.g. https://fakerjs.dev/api/internet.html#url

**Comment by CatMac228** [comment]
> Looks good! I think there are a few places that still need updating:
> 
> * 'getInitialTriageProjectsFromJira calls Jira API' test also needs to check to see if `scope` is included [here](https://github.com/Scottish-Tech-Army/Volunteer-app/blob/main/api/__tests__/cache/projects.test.js#L314)
> * There's [a file which creates test data for projects tests to use](https://github.com/Scottish-Tech-Army/Volunteer-app/blob/main/api/__test-data__/projects.js) which needs `scope` adding - [here](https://github.com/Scottish-Tech-Army/Volunteer-app/blob/main/api/__test-data__/projects.js#L28) and [here](https://github.com/Scottish-Tech-Army/Volunteer-app/blob/main/api/__test-data__/projects.js#L85) and [here](https://github.com/Scottish-Tech-Army/Volunteer-app/blob/main/api/__test-data__/projects.js#L166) I think (basically any objects where it's already providing a `video` property I think we need to add `scope` too?)

Thanks! Hopefully not missed anywhere this time 😀 I think the scope has already been added to the first one [here](https://github.com/Scottish-Tech-Army/Volunteer-app/blob/main/api/__tests__/cache/projects.test.js#L314) on line 315 (annoyingly can't seem to add a link to the files changed 😒)

**Review by joefhall — APPROVED** [review]
Nice one, thanks! 🚀  Hope you feel better soon!

**Review by DougieWougie — APPROVED** [review]
Tested with and without a connection to the dummy data, no problems.

**Pull request merged**
