### PR TITLE
Sva 213 es lint

### PR DESCRIPTION
**Pull request by rc-1988**
- [Description](#description)
  - [Type of change](#type-of-change)
- [Checklist](#checklist)

# Description

- This PR introduces linting into the CI pipeline. At this stage it only works on the ./app directory; if this is successful we can do similar for the ./api directory.
- Some linting checks (formatting, consistency in use of semicolons, etc) run as a pre-commit hook on staged files via [Husky](https://github.com/typicode/husky) and [lint-staged](https://github.com/okonet/lint-staged). At this point, ESLint may silently fix minor issues that it finds, or it may abort the commit and ask you to fix issues that it can't autofix. (Do we want the pre-commit hook, or do we want to just run everything on PR?)
- The same checks, plus an extra check to require a minimum level of JSDoc coverage, run at PR time on files that have been changed in the PR.
- Only files that have changed vs main are linted. This is so that we can introduce linting gradually without causing issues for work in progress.
- New dependencies: lint-staged, husky, prettier, various ESLint plugins

Fixes SVA-213

## Type of change

Please delete options that are not relevant
- [] Bug fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [] Breaking change(fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by joefhall** [comment]
Nice work @rc-1988!  Sounds really good.  (Not sure on your question about pre-commit vs. PR -- maybe we try it in action as is and could always change later if needed?)

Is there a way to test it in action, or does it need to be merged into `main` before it'll have an effect?

I also wondered: would it be worth adding to the docs that people should [install Prettier](https://www.digitalocean.com/community/tutorials/code-formatting-with-prettier-in-visual-studio-code) (and possibly also ESLint) extensions for VS Code?  I use Prettier with the 'Format on Save' option enabled, I find it's a massive time-saver and gets me in the habit of working with cleanly written code (was a bit of a halleluiah moment for me when I discovered it!)

**Review by M4RC1N76 — APPROVED** [review]
I have red the informations about the ESLint and familiarise myself what benefits this brings to the App. You have done a great work dealing with SVA 213 ESLint ticket. The mentioned above is a great help for app development especially (by novice developers) when we want to make sure that our code follows certain set of syntax conventions, or if we want to check the code for possible problems. Well done!!

**Comment by DougieWougie** [comment]
> Is there a way to test it in action, or does it need to be merged into `main` before it'll have an effect?

nektos/act can https://github.com/nektos/act

**Comment by M4RC1N76** [comment]
Hi Dougie, good question. I am working today and tomorrow. I will check if (or how) I can test it other way than using continuous integration test on github. I need to learn more about testing.

Sent from Yahoo Mail on Android 
 
  On Sat, 8 Oct 2022 at 10:38, Dougie ***@***.***> wrote:   



Is there a way to test it in action, or does it need to be merged into main before it'll have an effect?


nektos/act can https://github.com/nektos/act

**Comment by rc-1988** [comment]
Hi folks, sorry for the delay!

Re: testing, I've added a couple of commits that demonstrate the linting pipeline in action:

image

Commit #c01cadb fixes a couple of linter warnings about unnecessary escape characters ("useless" in ESLint's terminology - brutal!). However, because Validation.ts is then different from the version in main, it becomes subject to the linting checks, which fail because I didn't add the comments that the checks look for. (The cross comes up against the merge commit for some reason, but it's caused by the changes to Validation.ts.)

Commit #299a562 adds those necessary comments, so then the checks pass again.

You can manually trigger the CI checks to run again by going to the checks tab and using the "Re-run" button - thanks @jppferguson for the tip!

I'll add a readme update about Prettier now - thanks @joefhall for the suggestion.

**Review by DougieWougie — APPROVED** [review]
Great work @rc-1988 glad you persevered!

**Pull request merged**
