### PR TITLE
SVA-304 | Reduce crashes on project detail screen on Android when there's a video

### PR DESCRIPTION
**Pull request by joefhall**
- [Description](#description)
  - [Type of change](#type-of-change)
- [Testing locally](#testing-locally)
- [Checklist](#checklist)

# Description

- The project detail screen has been crashing sometimes on Android when it includes a video -- affects at least the emulator running on Linux, but potentially some real Android devices too
- Discovered it was the Android animation when the project detail screen is shown (that slight zoom effect you see) -- if the WebView component is already rendered it crashes the app.  Similar issues have been reported on real devices by others using the react-native-webview.
- Solution proposed is to very slightly delay the rendering of the WebView component (which shows the video) until after the screen has rendered and the Android animation has completed.
- Also added some other settings to the WebView component that are recommended by others who have experienced crashes in Android  with react-native-webview

Fixes # (issue number)

## Type of change

Please delete options that are not relevant

- [x] Bug fix (non-breaking change which fixes an issue)

# Testing locally

- Open a project detail screen that contains a video in your Android emulator

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have removed any unnecessary comments or console logging
- [] I have made corresponding changes to the documentation (if required)
- [] I have addressed accessibility, if needed
- [x] I have followed best practices, e.g. NativeBase approaches and theming
- [] I have checked the app in dark mode, if making front-end design changes
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by DougieWougie — APPROVED** [review]
Nice one @joefhall - I've checked it on Android against half a dozen videos, none are crashing.

**Comment by M4RC1N76** [comment]
HI @joefhall, while I was checking the videos in the project list I came across the one video which freezes after two seconds ("The Argyll and Sutherland Highlanders Museum- Interactive Map") is it my emulator or something's wrong with the video? Would you be able to check that?

**Comment by joefhall** [comment]
> HI @joefhall, while I was checking the videos in the project list I came across the one video which freezes after two seconds ("The Argyll and Sutherland Highlanders Museum- Interactive Map") is it my emulator or something's wrong with the video? Would you be able to check that?

Hi Marcin, thanks for looking at this.  That video works fine for me.  If videos keep freezing for you, worth raising this as a separate bug to look into.  This ticket I've been doing is about the app crashing entirely when it tries to open the project detail screen (before you get to actually playing a video).

**Comment by M4RC1N76** [comment]
I see. It is the only video that freezes after two seconds, the rest work fine (I have check every single one of theme). Great work Joe!!

**Review by M4RC1N76 — APPROVED** [review]
Great work @joefhall !!

**Pull request merged**
