### PR TITLE
SVA-382 | Fix API tunnelling bug on some Windows machines

### PR DESCRIPTION
**Pull request by joefhall**
- [Description](#description)
  - [Type of change](#type-of-change)
- [Testing locally](#testing-locally)
- [Checklist](#checklist)

# Description

- @vglampard  has been having problems getting the API tunnelling command to work on Windows.  This could affect other devs too and we want to make getting set up as simple and pain-free as possible.
- Updated the API tunnelling command to probably be more reliable generally, by using `cross-var` and `dotenv-cli` packages, so we can have a single command that works across different machines.

Fixes # SVA-382

## Type of change

Please delete options that are not relevant

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change(fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Testing locally

@vglampard has already tried this out on her Windows machine and I have on Linux - be great to get it tested on at least one other Windows machine, and on a Mac

- Pull this branch then in your `api` directory do `npm install`
- Make sure you have `API_TUNNEL_SUBDOMAIN` set in your `api/.env` file (see the README if needed)
- In one terminal window, in your `api` directory, run `npm start` like normal
- In a second terminal window, in your `api` directory, run `npm run tunnel`  (note the name of the command has changed). If that works, it should tell you something similar to `your url is: https://nadia-bloggs-abc123etc.loca.lt`
- Try that URL in a web browser with `/v1/projects` on the end (similar to `https://nadia-bloggs-abc123etc.loca.lt/v1/projects`)

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have removed any unnecessary comments or console logging
- [x] I have made corresponding changes to the documentation (if required)
- [] I have addressed accessibility, if needed
- [x] I have followed best practices, e.g. NativeBase approaches and theming
- [] I have checked the app in dark mode, if making front-end design changes
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [] I have updated the version numbers in `package.json` files in the [app](DEPLOYMENT.md#app-deployment) and/or [api](DEPLOYMENT.md#api-deployment-on-aws) directories as needed

### CODE REVIEW

**Review by DougieWougie — APPROVED** [review]
+1 for Codespaces.

**Comment by M4RC1N76** [comment]
Hi @joefhall , there was a one little thing I have noticed,  onceI have typed "npm run tunnel" the result was an error:
npm ERR! Missing script: "tunnel"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/marcin/.npm/_logs/2023-06-29T21_57_46_471Z-debug-0.log

I have reminded myself that we have used more specific command "npm run tunnel-mac-linux" for (mac users) there was also a windows users version "npm run tunnel-windows". After I have written the mentioned above command (for mac users) all worked fine. I hope it will be a helpful note. 

Nice work Joe!!

**Review by M4RC1N76 — APPROVED** [review]
Hi @joefhall , all works fine! I have also left a comment. Nice work!!

**Comment by joefhall** [comment]
Hi @M4RC1N76 thanks for reviewing.  I think that you weren't looking at the right branch if you couldn't run the `npm run tunnel` command (and this PR removes the `npm run tunnel-mac-linux` command.

Please can you checkout the branch `fix/more-reliable-api-tunnelling` (if you can't find it do `git fetch` then try again) then do `git pull`

Then go through the steps in 'Testing locally' (above) again.  Thanks

**Comment by M4RC1N76** [comment]
I have just realise that I was testing main. Thanks for pointing this out. I'll test the fix/more-reliable-api-tunnelling right now :-)

**Review by M4RC1N76 — APPROVED** [review]
Hi @joefhall. After doing npm install and running api (using npm run tunnel) I have tried URL in a web browser with /v1/projects on the end and it worked fine. Nice work Joe!

**Comment by joefhall** [comment]
Cheers @DougieWougie and @M4RC1N76 !

**Pull request merged**
