### PR TITLE
Removed client folder - no longer required

### PR DESCRIPTION
**Pull request by DougieWougie**
- [Description](#description)
  - [Type of change](#type-of-change)
- [Checklist](#checklist)

# Description

- Removed the no longer required client folder as discussed on the stand up
- Removed ci_client.yml (no longer need to test the client folder)
- Added ci_app.yml (now checks the app folder)

## Type of change

Please delete options that are not relevant
- [] Bug fix (non-breaking change which fixes an isssue)
- [] New Feature (non-breaking change which adds functionlity)
- [] Breaking change(fix or feature that would cause existing functionlity to not work as expected)
- [] This change requires a documentation update

# Checklist

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, pariculary in hard-to-understand areas
- [] I have made corresponding changes to the documentation (if required)
- [X] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by DougieWougie** [comment]
- [ ] Need to look at the Workflow ci_client.yml and update it to check the app folder rather than the client folder.

**Comment by joefhall** [comment]
Hi @DougieWougie I haven't been able to get the app to compile to an emulator recently, so am not able to test out your code unfortunately (although it makes sense from a look through).  I need to get that sorted out but it won't be till next week as things are a bit full-on -- hopefully other folks are able to test this for you and approve the PR.

**Comment by DougieWougie** [comment]
Not a problem Joe, thanks anyway! It's unusually quiet at work today...

**Review by CatMac228 — APPROVED** [review]
Compiled with no issues :)

**Review by jppferguson — APPROVED** [review]
Looks good to me @DougieWougie  👍🏻

**Pull request merged**
