### PR TITLE
Applied dark mode to welcome screen

### PR DESCRIPTION
**Pull request by treneff**
- [Description](#description)
  - [Type of change](#type-of-change)
- [Testing locally](#testing-locally)
- [Checklist](#checklist)

# Description

- Applied native base components to heading and text responding to theme change on the Welcome screen.

Fixes # (SVA278)

## Type of change

Please delete options that are not relevant

- [] Bug fix (non-breaking change which fixes an issue)

# Checklist

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have removed any unnecessary comments or console logging
- [] I have made corresponding changes to the documentation (if required)
- [] I have addressed accessibility, if needed
- [] I have followed best practices, e.g. NativeBase approaches and theming
- [] I have checked the app in dark mode, if making front-end design changes
- [] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by joefhall — CHANGES_REQUESTED** [review]
Nice work @treneff @M4RC1N76!  I'd thought it would be too much of a pain to be worth getting things like `adjustsFontSizeToFit` working with NativeBase components, but your approach is better than the one I suggested.

Can you fix the text in the STA logo at the top of these same welcome screens too please?

And could you fix this initial welcome screen too, where the text colour also isn't right in dark mode?  (in `StartupContainer`)
Screenshot 2023-03-26 17 06 11 - Display 2

**Review by M4RC1N76 — APPROVED** [review]
Great work @treneff!! I have done some adjustments of colour and Welcome text in the Startup Screen as discussed on slack.

**Review by M4RC1N76 — COMMENTED** [review]
Hi @joefhall and @DougieWougie ,I have applied the necessary changes listed in the change request. However, I am not sure how to resolve date type issue in app/src/Components/Welcome/WelcomeSlider.tsx. Interface SliderProps lines 40 to 45 (41 and 44 to be specific). I tired to find the solution online and in our App. Could someone suggest some sort of solution. how to use more specific data type instead of 'Function' and <Object> which are to generic, please?

**Comment by joefhall** [comment]
> Hi @joefhall and @DougieWougie ,I have applied the necessary changes listed in the change request. However, I am not sure how to resolve date type issue in app/src/Components/Welcome/WelcomeSlider.tsx. Interface SliderProps lines 40 to 45 (41 and 44 to be specific). I tired to find the solution online and in our App. Could someone suggest some sort of solution. how to use more specific data type instead of 'Function' and which are to generic, please?

Hi @M4RC1N76 I think the correct types there should be...
```
interface SliderProps {
  setActiveIndex: Dispatch<SetStateAction<number>>
  windowWidth: number
  slideRef: Ref<null>
  slides: WelcomeSlide[]
  isAndroidRTL: boolean
}
```

(I didn't know the correct type for `setActiveIndex` so I used a little trick: hovered my mouse over it where it's defined in WelcomeContainer.tsx, and VS Code told me what type to use.  That doesn't always work, but can come in handy particularly with obscure types from external libraries.  Also worth knowing -- I don't think you normally use `Function` as a type in Typescript, it's usually something like `() => void` or `(text: string) => string` depending on what types the function takes as parameters and what type it returns.)

if you also...

...update the React import statement at the top of WelcomeSlider.tsx to: `import React, { Dispatch, FC, Ref, SetStateAction } from 'react'`

...add this import statement at the top of WelcomeSlider.tsx: `import { WelcomeSlide } from './WelcomeSlides'`

...add this to WelcomeSlides.tsx:
```
export interface WelcomeSlide {
  image: JSX.Element
  title: string
  text: string
}
```

...change the penultime line of WelcomeSlides.tsx from `]` to `] as WelcomeSlide[]`

I'm seeing a few other Typescript errors in WelcomeSlider.tsx but honestly I'm not sure it's worth trying to solve everything at this point (there are other non-Typescript issues with these welcome screens too, not related to anything you've done).   We're going to be replacing these welcome screens soon in MVP+1.

**Comment by M4RC1N76** [comment]
Thank you @DougieWougie and @joefhall for your insight. I have applied the changes you both have suggested.

**Comment by joefhall** [comment]
Hi @M4RC1N76 you've missed off the last thing I suggested (it's line 41):

...change the penultime line of WelcomeSlides.tsx from ] to ] as WelcomeSlide[]

Also I see there's a merge conflict in WelcomeButton.tsx -- are you able to resolve that or do you need help?

**Comment by M4RC1N76** [comment]
I would need help with that. I had an attempt earlier, however I think it would have cause more issues than fix the problem if I had proceed with it.    On Monday, 17 April 2023 at 13:25:50 BST, Joe Derry Hall ***@***.***> wrote:  
 
 


Hi @M4RC1N76 you've missed off the last thing I suggested (it's line 41):

...change the penultime line of WelcomeSlides.tsx from ] to ] as WelcomeSlide[]

Also I see there's a merge conflict in WelcomeButton.tsx -- are you able to resolve that or do you need help?

**Review by joefhall — APPROVED** [review]
Nice one @treneff and @M4RC1N76 -- thanks!

(As discussed with Marcin, there are still a few stray files in here that shouldn't be part of this PR, but they're either just little bits of code formatting or old projects components that will be removed shortly anyway, so reckon it's best just to get this PR approved and merged.)

**Pull request merged**
